CREATE TABLE accumulated_expense_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    money_accumolated DOUBLE PRECISION,
    os_number INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE base_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    latitude VARCHAR(255),
    longitude VARCHAR(255),
    adress VARCHAR(255),
    area VARCHAR(255),
    unit TINYINT CHECK (unit BETWEEN 0 AND 21),
    PRIMARY KEY (id)
);

CREATE TABLE technical_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    car VARCHAR(255),
    contract INTEGER,
    is_working BOOLEAN NOT NULL,
    km_carxl DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    name VARCHAR(255),
    os_number INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE os_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    area VARCHAR(255),
    contract INTEGER,
    distance_base_os DOUBLE PRECISION,
    is_enable BOOLEAN NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    occurrence VARCHAR(255),
    os_number INTEGER,
    responsible_screening VARCHAR(255),
    screening_date DATE,
    unit TINYINT CHECK (unit BETWEEN 0 AND 21),
    technical_id INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT FK_os_technical
        FOREIGN KEY (technical_id)
        REFERENCES technical_entity (id)
);
INSERT INTO technical_entity (
    car,
    contract,
    is_working,
    km_carxl,
    latitude,
    longitude,
    name,
    os_number
) VALUES (
    'Fiat Uno',
    12345,
    TRUE,
    12.5,
    -22.90,
    -43.20,
    'João Silva',
    100100
);

INSERT INTO os_entity (
    contract,
    os_number,
    occurrence,
    unit,
    screening_date,
    distance_base_os,
    area,
    latitude,
    longitude,
    responsible_screening,
    is_enable,
    technical_id
) VALUES (
    12345,
    100100,
    'Reparo',
    1,
    DATE '2025-01-01',
    5.0,
    '5.1',
    -22.527860,
    -43.174521,
    'José',
    TRUE,
    1
);

INSERT INTO os_entity (
    contract,
    os_number,
    occurrence,
    unit,
    screening_date,
    distance_base_os,
    area,
    latitude,
    longitude,
    responsible_screening,
    is_enable,
    technical_id
) VALUES (
    89276,
    101010,
    'Reparo',
    3,
    DATE '2025-01-07',
    12.8,
    '5.1',
    -21.940511,
    -42.605530,
    'Luiz',
    TRUE,
    1
);

INSERT INTO os_entity (
    contract,
    os_number,
    occurrence,
    unit,
    screening_date,
    distance_base_os,
    area,
    latitude,
    longitude,
    responsible_screening,
    is_enable,
    technical_id
) VALUES (
    2982,
    200300,
    'Upgrade',
    2,
    DATE '2025-01-03',
    7.6,
    '5.1',
    -22.285239,
    -42.532968,
    'Rafael',
    TRUE,
    1
);